name: magebridgecore_devcontainer
services:
  joomla:
    build:
      context: ./joomla
    image: joomla:magebridge
    volumes:
      - type: volume
        source: joomla_data
        target: /var/www/html
      - type: volume
        source: joomla_log
        target: /var/www/html/administrator/logs
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}
        target: /workspace
        consistency: cached
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.devcontainer/php.ini
        target: /usr/local/etc/php/php.ini
        read_only: true
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.vscode
        target: /var/www/html/.vscode
        consistency: cached
    environment:
      JOOMLA_DB_HOST: ${JOOMLA_DB_HOST:-mysql}
      JOOMLA_DB_PASSWORD: ${JOOMLA_DB_PASSWORD:-${MYSQL_ROOT_PASSWORD:-secret}}
      # https://xdebug.org/docs/all_settings
      # XDEBUG_CONFIG: 'client_host=localhost log=/tmp/xdebug.log'
      # XDEBUG_MODE: debug
    ports:
      - 127.0.0.1:80:80
    networks:
      default:
        aliases:
          - www.dev.local
    depends_on:
      - mysql

  openmage:
    build:
      context: ./openmage
    image: openmage:magebridge
    volumes:
      - type: volume
        source: openmage_data
        target: /var/www/html
      - type: volume
        source: openmage_log
        target: /var/www/html/var/logs
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}
        target: /var/www/html/.modman/MageBridge
        consistency: cached
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.devcontainer/php.ini
        target: /usr/local/etc/php/php.ini
        read_only: true
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.vscode
        target: /var/www/html/.vscode
        consistency: cached
    # environment:
      # https://github.com/OpenMage/magento-lts/blob/32773dd4f82bb44bac89e8eca97379dad2a10af5/app/Mage.php#L22
      # MAGE_IS_DEVELOPER_MODE: '1'
      # https://xdebug.org/docs/all_settings
      # XDEBUG_CONFIG: 'client_host=localhost log=/tmp/xdebug.log'
      # XDEBUG_MODE: debug
    ports:
      - 127.0.0.1:8080:8080
    networks:
      default:
        aliases:
          - store.dev.local
    depends_on:
      - mysql

  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-openmage}
    ports:
      - 127.0.0.1:3306:3306

volumes:
  joomla_data: null
  joomla_log: null
  mysql_data: null
  openmage_data: null
  openmage_log: null
