name: Build Docker images

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'
  pull_request:
    branches:
      - main
    paths:
      - '.devcontainer/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          cd .devcontainer
          docker compose build
