name: 'Linting PHP'

on:
  push:
    branches:
      - 1.9.x
    paths:
      - '**.php'
      - '**.phtml'
  pull_request:
    branches:
      - 1.9.x
    paths:
      - '**.php'
      - '**.phtml'
  # Allow manually triggering the workflow.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
      - name: Linting PHP files
        run: '! find . -type f -name "*.php" -exec php -d display_errors=1 -d error_reporting=-1 -l {} \; 2>&1 | grep -v ^"No syntax errors"'
      - name: Linting PHTML files
        run: '! find ./magento/app/design -type f -name "*.phtml" -exec php -d display_errors=1 -d error_reporting=-1 -l {} \; 2>&1 | grep -v ^"No syntax errors"'
